//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blurb
    {
        public Blurb()
        {
            this.Translations = new HashSet<Translation>();
        }
    
        public int BlurbId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string DefaultText { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
