//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlurbDBEntities : DbContext
    {
        public BlurbDBEntities()
            : base("name=BlurbDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Blurb> Blurbs { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Culture> Cultures { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCulture_lnk> ProductCulture_lnk { get; set; }
        public DbSet<Translation> Translations { get; set; }
    }
}
