//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Blurbs = new HashSet<Blurb>();
            this.Category1 = new HashSet<Category>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public int ProductId { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime SaveDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Blurb> Blurbs { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
