//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public Culture()
        {
            this.ProductCulture_lnk = new HashSet<ProductCulture_lnk>();
            this.Translations = new HashSet<Translation>();
        }
    
        public int CultureId { get; set; }
        public string CultureCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ProductCulture_lnk> ProductCulture_lnk { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
