//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Categories = new HashSet<Category>();
            this.ProductCulture_lnk = new HashSet<ProductCulture_lnk>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime SaveDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<ProductCulture_lnk> ProductCulture_lnk { get; set; }
    }
}
