//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E1Blurbs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int TranslationId { get; set; }
        public int BlurbId { get; set; }
        public int CultureId { get; set; }
        public string LanguageCode { get; set; }
        public string Text { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Blurb Blurb { get; set; }
        public virtual Culture Culture { get; set; }
    }
}
